article = document.getElementById(cart__items);
article = document.createElement(article);
article.setAttribute("class","cart__item");
article.setAttribute("datat-id","product-ID");
article.setAttribute("data-color","product-color");
cart__items.appendChild(article);
div = document.getElementById(cart__items);
div1 = document.createElement(div);
div1.setAttribute("class","cart__item__img");
article.appendChild(div1);
img = document.getElementById(cart__items);
img = document.createElement(img);
img.src = "../images/product01.jpg";
img.alt="photographie d'un canapé";
div1.appendChild(img);
div = document.createElement(div);
div.setAttribute("class","cart__item__content");
article.appendChild(div);
div = document.getElementById(cart__items);
div2 = document.createElement(div);
div2.setAttribute("class","cart__item__content__description");
div1.appendChild(div2);
h2 = document.getElementById(cart__items);
h2 = document.createElement(h2);
h2.innerHTML = "nom du produit";
div2.appendChild(h2);
p = document.getElementById(cart__items);
p = document.createElement(p);
p.innerHTML = "Vert";
div2.appendChild(p);
p = document.getElementById(cart__items);
p2 = document.createElement(p);
p2.innerHTML = "42,00€";
div2.appendChild(p2);
div3 = document.createElement(div);
div3.setAttribute("class","cart__item__content__settings");
article.appendChild(div3);
div4 = document.createElement(div);
div4.setAttribute("class","cart__item__content__settings__quantity");
div4.appendChild(div3);
p = document.createElement(p);
p.innerHTML = "Qté :";
div4.appendChild(p);
input = document.getElementById(cart__items);
input = document.createElement(input);
input.setAttribute("type","number");
input.setAttribute("class","itemQuantity");
input.setAttribute("name","itemQuantity");
input.setAttribute("min","1");
input.setAttribute("max","100");
input.setAttribute("value","42");
div4.appendChild(input);
div5 = document.createElement(div);
div5.setAttribute("class","cart__item__content__settings__delete");
article.appendChild(div5);
p = document.getElementById(cart__items);
p3 = document.createElement(p);
p3.setAttribute("class", "deleteItem");
p3.innerHTML = "Supprimer";
div5.appendChild(p3);




